/**
 * Single source of truth for shared, editor-facing website copy.
 *
 * Keep paths, permissions and other behavioral constants in their owning
 * modules. Human-facing labels, headings and descriptions belong here.
 */
export const siteCopy = {
  metadata: {
    title: "北京大学人工智能研究院综合服务系统 | Artificial Intelligence Agora",
    titleTemplate: "%s | Artificial Intelligence Agora",
    description: "The Integrated Services Platform of PKU IAI — 北京大学人工智能研究院综合服务系统。",
    shortDescription: "The Integrated Services Platform of PKU IAI",
    keywords: ["人工智能", "北京大学", "北京大学人工智能研究院", "AIA", "Artificial Intelligence Agora", "PKU IAI"],
    author: "北京大学人工智能研究院",
    siteName: "Artificial Intelligence Agora",
    twitterTitle: "Artificial Intelligence Agora | PKU IAI",
  },
  brand: {
    aiaShort: "AIA",
    aiaName: "北京大学人工智能研究院",
    aiaHomeLabel: "北京大学人工智能研究院 AIA 首页",
    aiaLogoAlt: "北京大学人工智能研究院 AIA 标识",
    tongClassName: "通用人工智能实验班",
    tongClassLogoAlt: "通用人工智能实验班标识",
    graduateIntranetName: "人工智能研究院研究生内网",
    graduateIntranetLogoAlt: "人工智能研究院研究生内网标识",
    graduateIntranetEnglish: "Graduate Intranet",
  },
  common: {
    login: "登录",
    logout: "退出登录",
    notifications: "通知",
    search: "站内搜索",
    intranet: "内网",
    intranetEntry: "内网入口",
    accountSettings: "账户设置",
    personalAcademic: "个人学术",
    adminConsole: "管理后台",
    openAccountMenu: "打开账户菜单",
    loading: "Loading...",
    returnHome: "返回首页",
  },
  navigation: {
    aia: [
      { name: "研究院", href: "/institute" },
      { name: "人员", href: "/people" },
      { name: "团队", href: "/groups" },
      { name: "研究", href: "/research" },
      { name: "动态", href: "/updates" },
    ],
    aiaDesktopLabel: "AIA 主导航",
    aiaMobileLabel: "AIA 移动导航",
    openAiaMenu: "打开 AIA 导航菜单",
    closeAiaMenu: "关闭 AIA 导航菜单",
    tongClass: [
      { name: "关于通班", key: "about" },
      { name: "动态", key: "news" },
      { name: "成员", key: "members" },
      { name: "成果", key: "publications" },
      { name: "资源", key: "resources" },
      { name: "课程", key: "courses", auth: true },
      { name: "活动", key: "events", auth: true },
      { name: "内网", key: "intranet", auth: true, loggedInOnly: true },
    ],
    graduate: [
      { name: "成员", key: "members", auth: true },
      { name: "活动", key: "events", auth: true },
      { name: "内网", key: "intranet", auth: true, loggedInOnly: true },
    ],
    tongClassDesktopLabel: "通班主导航",
    openTongClassMenu: "打开通班导航菜单",
    closeTongClassMenu: "关闭通班导航菜单",
  },
  portal: {
    kicker: "内网 · Intranet",
    title: "内网",
    loadingLogin: "正在确认登录状态…",
    loadingPermissions: "正在确认班级工作权限…",
    signedOutDescription: "内网在同一研究院外壳下，按你的账户身份呈现通知、Coffee Talk、通班与管理模块。请先登录以继续。",
    loginAction: "登录并进入内网",
    greetingPrefix: "你好，",
    defaultIdentity: "研究院用户",
    identity: { classMember: "通班成员", teacher: "教师" },
    modules: {
      coffeeTalk: { title: "Coffee Talk", description: "申请教师交流并查看相关办理进度。" },
      oa: { title: "OA 与审批", description: "办理研究院表单、材料提交与审批事项。" },
      graduateIntranet: { title: "人工智能研究院研究生内网", description: "查看研究生成员、活动与专属内网工具。" },
      publications: { title: "个人学术", description: "维护你的公开学术成果与研究方向。" },
      publicProfile: { description: "查看你在平台中已公开且经过验证的个人页面。" },
      settings: { title: "账户设置", description: "管理账户资料、安全与偏好设置。" },
      classIntranet: { title: "通班内网", description: "表单、报销、资料与树洞等班级内部事务。" },
      courses: { title: "通班课程", description: "课程信息、讲义与课程评价。" },
      events: { title: "通班活动", description: "班级活动安排与记录。" },
      createNews: { title: "创建新闻", description: "撰写新闻并提交给有审核与管理权的成员审批。" },
      reviewExternalNews: { title: "审阅官网新闻", description: "核对机器人生成的官网新闻草稿，修改后交给发布管理员审批。" },
      manageNews: { title: "管理新闻", description: "审核待发布新闻并查看处理记录。" },
      createEvent: { title: "创建活动", description: "创建活动信息并提交审批。" },
      manageEvent: { title: "管理活动", description: "审核待发布活动并查看处理记录。" },
      createReimbursement: { title: "创建报销表单", description: "创建自定义报销表单，并配置可见范围与审批流程。" },
      reviewReimbursement: { title: "审核报销", description: "前往 OA 审批处理台审核报销事项。" },
      forms: { title: "表单管理", description: "创建并发布面向研究院成员的表单，设定可见范围并查看提交记录。" },
      researchGroupsTeacher: { title: "课题组管理", description: "维护本课题组成员、文章与公开资料。" },
      researchGroupsAdmin: { title: "课题组管理", description: "选择并维护课题组成员、文章与公开资料。" },
      admin: { title: "管理后台", description: "内容、账户与研究院目录的管理入口。" },
      permissions: { title: "权限管理", description: "配置新闻、活动与报销的创建权和审核管理权。" },
      newsSync: { title: "官网新闻同步", description: "管理固定栏目同步、审阅范围、观察模式与运行健康状态。" },
      organization: { title: "组织管理", description: "新建、管理与删除用户组，用于表单可见范围与审批范围。" },
    },
    sections: {
      common: { kicker: "通用", title: "与你相关", blurb: "日常高频入口 — 交流申请、审批办理、个人学术与账户。" },
      class: { kicker: "通班", title: "班级事务", blurb: "通班内部事务 — 表单报销、课程与班级活动。" },
      classWork: { kicker: "班级工作", title: "班级工作", blurb: "根据平台授权创建或审核新闻、活动与报销事项。" },
      teacher: { kicker: "教师", title: "教学服务", teacherBlurb: "面向教师的教学与课题组管理工具。", adminBlurb: "研究院表单与教学服务管理工具。" },
      admin: { kicker: "管理", title: "平台管理", blurb: "平台内容、账户与目录的管理入口。" },
    },
  },
  intranet: {
    heroLabel: "INTRANET",
    graduateTitle: "研究生内网",
    classTitle: "内部网站",
    graduateDescription: "面向人工智能研究院研究生的内部工具入口。",
    classDescription: "这是一个仅面向通班成员的内部网站，包含内部论坛、意见反馈、内部工具和协作入口等内容。请不要将此网页的内部资源分享到公开渠道哦～",
    empty: "暂无可展示的内网模块。",
    guard: {
      loginTitle: "需要登录后访问",
      loginDescription: "请先使用学号登录后再访问此页面。",
      loading: "Loading...",
      loginAction: "前往登录",
      deniedTitle: "仅限通班成员",
      deniedDescription: "当前账户已登录，但尚未被标记为通班成员。如身份信息有误，请联系管理员核验。",
      returnAction: "返回内网",
    },
    modules: {
      treehole: { title: "通班树洞", description: "面向通班成员的内部讨论区。可以实名或匿名发帖、回复，交流学习生活中的想法、困惑......" },
      feedback: { title: "意见反馈", description: "用于收集同学们对通班学习、科研、课程、活动、组织运行等方面的建议，管理员会定期收集整理并向院办/管委会汇报。" },
      wps: { title: "通班工作 WPS", description: "想参与通班自治委员会工作的同学，可在这里申请加入通班 WPS workspace，获得历年学生工作材料资源。" },
      techday: { title: "TechDay 科技节平台", description: "科技节成果展示、投稿管理、评奖、报销和外部作者/志愿者注册入口。内部成员可直接使用通班账号进入。" },
      challenge: { title: "智慧通班创意开发挑战赛2026", description: "2026通班创意开发挑战赛入口，诚邀你来一起建设智慧通班！" },
      materials: { title: "资料下载", description: "通班相关的各种内部资料下载，包括但不限于培养方案、报销政策文件等。" },
      reimbursements: { title: "报销", description: "学术交流支持、学生活动等报销申请入口。" },
      forms: { title: "OA 填报", description: "查看正在发布的问卷、申请和报销类表单，提交材料并跟踪审核结果。" },
    },
  },
  footer: {
    aiaKicker: "AIA · Artificial Intelligence Agora",
    aiaTitle: "北京大学人工智能研究院",
    aiaDescription: "北京大学人工智能研究院综合服务系统 — The Integrated Services Platform of PKU IAI",
    instituteHeading: "研究院",
    contactHeading: "联系与平台",
    address: "北京市海淀区北京大学资源西楼 2205",
    instituteLinks: [
      { name: "研究院概况", href: "/institute" },
      { name: "人员目录", href: "/people" },
      { name: "研究团队", href: "/groups" },
      { name: "研究成果", href: "/research" },
    ],
    platformLinks: [
      { name: "最新动态", href: "/updates" },
      { name: "通班", href: "/tong-class" },
      { name: "联系研究院", href: "/contact" },
    ],
    copyrightPrefix: "©",
    tongClassName: "北京大学 & 清华大学 通用人工智能实验班",
    tongClassCopyright: "Tong Class. All rights reserved.",
  },
} as const

export type SiteCopy = typeof siteCopy
